# Generated by Django 5.1.5 on 2025-02-04 01:29
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("facture", "0001_initial"),
        ("flyauth", "0002_alter_flyuser_disabled_customer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_invoice_attributed",
                to="flyauth.customer",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_invoice",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
