# Generated by Django 5.1.5 on 2025-02-11 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0004_invoice_created_at_invoice_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='facture',
            field=models.ForeignKey(db_column='facture_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_article', to='facture.invoice', verbose_name='invoice'),
            preserve_default=False,
        ),
    ]
