# Generated by Django 5.1.5 on 2025-02-09 20:09
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("facture", "0004_invoice_created_at_invoice_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="article",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_article",
                to="facture.article",
                verbose_name="article",
            ),
        ),
    ]
