# Generated by Django 5.1.5 on 2025-02-09 20:14
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("facture", "0005_invoice_article"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="article",
        ),
        migrations.AddField(
            model_name="invoice",
            name="article",
            field=models.ManyToManyField(
                null=True,
                related_name="invoice_article",
                to="facture.article",
                verbose_name="article",
            ),
        ),
    ]
