# Generated by Django 5.1.5 on 2025-02-11 14:25
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("facture", "0006_remove_invoice_article_invoice_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="article",
            field=models.ManyToManyField(
                related_name="invoice_article",
                to="facture.article",
                verbose_name="article",
            ),
        ),
    ]
