# Generated by Django 5.1.5 on 2025-02-22 21:25
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("facture", "0007_alter_invoice_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="final date"
            ),
        ),
    ]
