# Generated by Django 5.1.5 on 2025-02-04 01:49
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("flyauth", "0002_alter_flyuser_disabled_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_customer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
