# Generated by Django 5.1.5 on 2025-02-11 14:25
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flyauth", "0003_customer_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="password",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="user_permissions",
        ),
    ]
