# Generated by Django 5.1.5 on 2025-02-11 14:46
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flyauth", "0004_remove_customer_groups_remove_customer_password_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="is_staff",
        ),
    ]
