# Generated by Django 5.1.5 on 2025-02-11 14:49
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flyauth", "0005_remove_customer_is_active_remove_customer_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="last_login",
        ),
    ]
