# Generated by Django 5.1.5 on 2025-02-11 14:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("flyauth", "0006_remove_customer_is_superuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="adress",
            field=models.CharField(
                blank=True, max_length=152, verbose_name="customer adress"
            ),
        ),
    ]
