# Generated by Django 5.1.5 on 2025-02-22 22:24
import phonenumber_field.modelfields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("flyauth", "0007_customer_adress"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="customer phone"
            ),
        ),
        migrations.AlterField(
            model_name="flyuser",
            name="id",
            field=models.UUIDField(
                primary_key=True, serialize=False, unique=True, verbose_name="user ID"
            ),
        ),
        migrations.AddIndex(
            model_name="flyuser",
            index=models.Index(fields=["email"], name="flyauth_fly_email_e1e89f_idx"),
        ),
    ]
