# Generated by Django 5.1.5 on 2025-02-22 22:30
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("flyauth", "0008_customer_phone_alter_flyuser_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flyuser",
            name="is_confirmed",
            field=models.BooleanField(default=False, verbose_name="is disabled"),
        ),
    ]
